/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module \(null) (pi0, pi1, pi2, pi3, pi4, pi5, po0, po1, po2, po3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input pi0;
  input pi1;
  input pi2;
  input pi3;
  input pi4;
  input pi5;
  output po0;
  output po1;
  output po2;
  output po3;
  assign _05_ = ~(pi3 & pi0);
  assign _00_ = _05_ ^ pi4;
  assign _01_ = pi1 & pi3;
  assign _02_ = _01_ & pi5;
  assign _03_ = ~(pi2 & pi1);
  assign _04_ = _02_ ? pi2 : _03_;
  assign po2 = _04_ ^ _00_;
  assign po3 = _01_ ^ pi5;
  assign po0 = 1'h0;
  assign po1 = 1'h1;
endmodule
