/* Generated by Yosys 0.34+27 (git sha1 7d30f716e, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module adder_i4_o3_lpp0_ppo1_et3_SOP1_iter1(in3, in2, in1, in0, out0, out1, out2);
  wire _0_;
  wire _1_;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  assign _0_ = ~(in1 & in3);
  assign out2 = ~_0_;
  assign _1_ = ~(in0 & in2);
  assign out1 = ~_1_;
  assign out0 = 1'h1;
endmodule
