/* Generated by Yosys 0.9+4052 (git sha1 a5adb007, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:1.1-45.10" *)
module adder_i4_o3(in0, in1, in2, in3, out0, out1, out2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:2.7-2.10" *)
  input in0;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:2.12-2.15" *)
  input in1;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:2.17-2.20" *)
  input in2;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:2.22-2.25" *)
  input in3;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:3.8-3.12" *)
  output out0;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:3.14-3.18" *)
  output out1;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:3.20-3.24" *)
  output out2;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:11.24-11.31" *)
  wire p_o2_t0;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:11.33-11.40" *)
  wire p_o3_t0;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:9.24-9.29" *)
  wire w_g10;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:5.6-5.11" *)
  wire w_g15;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:5.62-5.67" *)
  wire w_g23;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:5.69-5.74" *)
  wire w_g24;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:9.18-9.22" *)
  wire w_g9;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:7.27-7.32" *)
  wire w_in0;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:7.20-7.25" *)
  wire w_in1;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:7.13-7.18" *)
  wire w_in2;
  (* src = "adder_i4_o3_lpp2_ppo1_et6_SOP1.v:7.6-7.11" *)
  wire w_in3;
  assign _04_ = in0 | ~(in1);
  assign _05_ = in2 & ~(_04_);
  assign _00_ = ~(_05_ & in3);
  assign _01_ = ~(_00_ | in2);
  assign _02_ = ~(in3 & in1);
  assign out2 = _02_ | _01_;
  assign out1 = in2 & ~(_00_);
  assign _03_ = ~(in1 & in2);
  assign out0 = in3 & ~(_03_);
  assign p_o2_t0 = 1'h1;
  assign p_o3_t0 = in3;
  assign w_g10 = in3;
  assign w_g15 = out0;
  assign w_g23 = out1;
  assign w_g24 = out2;
  assign w_g9 = 1'h1;
  assign w_in0 = in0;
  assign w_in1 = in1;
  assign w_in2 = in2;
  assign w_in3 = in3;
endmodule
