/* Generated by Yosys 0.9+4052 (git sha1 a5adb007, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module top(in0, in1, in2, in3, out0, out1, out2, out3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input in0;
  input in1;
  input in2;
  input in3;
  output out0;
  output out1;
  output out2;
  output out3;
  wire w_out0;
  assign _08_ = ~(in2 & in0);
  assign out0 = ~_08_;
  assign w_out0 = ~_08_;
  assign _00_ = ~(in3 & in1);
  assign _01_ = ~_00_;
  assign _02_ = ~(in2 & in1);
  assign _03_ = ~(in0 & in3);
  assign _04_ = ~(w_out0 & _01_);
  assign out3 = ~_04_;
  assign _05_ = ~(_02_ & _03_);
  assign _06_ = ~(_04_ & _05_);
  assign out1 = ~_06_;
  assign _07_ = ~(_08_ & _01_);
  assign out2 = ~_07_;
endmodule
