/* Generated by Yosys 0.53+60 (git sha1 209df95fb, g++ 10.5.0-1ubuntu1~20.04 -fPIC -O3) */

module graph(in0, in1, in2, in3, in4, in5, in6, in7, out0, out1, out2, out3, out4, out5, out6, out7);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input in4;
  wire in4;
  input in5;
  wire in5;
  input in6;
  wire in6;
  input in7;
  wire in7;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  output out4;
  wire out4;
  output out5;
  wire out5;
  output out6;
  wire out6;
  output out7;
  wire out7;
  NAND2X1 _54_ (
    .A(_27_),
    .B(_24_),
    .Y(_31_)
  );
  NAND2X1 _55_ (
    .A(_23_),
    .B(_28_),
    .Y(_32_)
  );
  NAND2X1 _56_ (
    .A(_31_),
    .B(_32_),
    .Y(_48_)
  );
  NAND2X1 _57_ (
    .A(_27_),
    .B(_25_),
    .Y(_33_)
  );
  AOI22X1 _58_ (
    .A(_23_),
    .B(_29_),
    .C(_28_),
    .D(_24_),
    .Y(_34_)
  );
  NAND2X1 _59_ (
    .A(_33_),
    .B(_34_),
    .Y(_49_)
  );
  AOI22X1 _60_ (
    .A(_27_),
    .B(_26_),
    .C(_24_),
    .D(_29_),
    .Y(_35_)
  );
  NAND2X1 _61_ (
    .A(_23_),
    .B(_30_),
    .Y(_36_)
  );
  NAND2X1 _62_ (
    .A(_28_),
    .B(_25_),
    .Y(_37_)
  );
  NAND3X1 _63_ (
    .A(_35_),
    .B(_36_),
    .C(_37_),
    .Y(_50_)
  );
  INVX1 _64_ (
    .A(_35_),
    .Y(_38_)
  );
  INVX1 _65_ (
    .A(_37_),
    .Y(_39_)
  );
  NAND3X1 _66_ (
    .A(_38_),
    .B(_36_),
    .C(_39_),
    .Y(_40_)
  );
  NAND2X1 _67_ (
    .A(_25_),
    .B(_30_),
    .Y(_41_)
  );
  NAND3X1 _68_ (
    .A(_37_),
    .B(_29_),
    .C(_26_),
    .Y(_42_)
  );
  NAND3X1 _69_ (
    .A(_40_),
    .B(_41_),
    .C(_42_),
    .Y(_52_)
  );
  AND2X2 _70_ (
    .A(_23_),
    .B(_27_),
    .Y(_47_)
  );
  NAND2X1 _71_ (
    .A(_25_),
    .B(_29_),
    .Y(_43_)
  );
  NAND2X1 _72_ (
    .A(_28_),
    .B(_26_),
    .Y(_44_)
  );
  NOR2X1 _73_ (
    .A(_43_),
    .B(_44_),
    .Y(_53_)
  );
  NAND2X1 _74_ (
    .A(_24_),
    .B(_30_),
    .Y(_45_)
  );
  NAND3X1 _75_ (
    .A(_43_),
    .B(_44_),
    .C(_45_),
    .Y(_46_)
  );
  AND2X2 _76_ (
    .A(_40_),
    .B(_46_),
    .Y(_51_)
  );
  assign out7 = 1'h0;
  assign _23_ = in0;
  assign _28_ = in5;
  assign _27_ = in4;
  assign _24_ = in1;
  assign out1 = _48_;
  assign _25_ = in2;
  assign _29_ = in6;
  assign out2 = _49_;
  assign _26_ = in3;
  assign _30_ = in7;
  assign out3 = _50_;
  assign out5 = _52_;
  assign out0 = _47_;
  assign out6 = _53_;
  assign out4 = _51_;
endmodule
