/* Generated by Yosys 0.53+60 (git sha1 209df95fb, g++ 10.5.0-1ubuntu1~20.04 -fPIC -O3) */

module graph(in0, in1, in2, in3, out0, out1, out2, out3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  INVX1 _15_ (
    .A(_06_),
    .Y(_10_)
  );
  INVX1 _16_ (
    .A(_03_),
    .Y(_07_)
  );
  NAND2X1 _17_ (
    .A(_04_),
    .B(_05_),
    .Y(_08_)
  );
  OAI21X1 _18_ (
    .A(_10_),
    .B(_07_),
    .C(_08_),
    .Y(_12_)
  );
  AND2X2 _19_ (
    .A(_03_),
    .B(_05_),
    .Y(_11_)
  );
  NOR3X1 _20_ (
    .A(_08_),
    .B(_10_),
    .C(_07_),
    .Y(_14_)
  );
  INVX1 _21_ (
    .A(_04_),
    .Y(_09_)
  );
  NOR3X1 _22_ (
    .A(_10_),
    .B(_11_),
    .C(_09_),
    .Y(_13_)
  );
  assign _06_ = in3;
  assign _03_ = in0;
  assign _04_ = in1;
  assign _05_ = in2;
  assign out1 = _12_;
  assign out0 = _11_;
  assign out3 = _14_;
  assign out2 = _13_;
endmodule
