/* Generated by Yosys 0.53+60 (git sha1 209df95fb, g++ 10.5.0-1ubuntu1~20.04 -fPIC -O3) */

module top(in0, in1, in2, in3, out0, out1, out2, out3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  AND2X2 _14_ (
    .A(_03_),
    .B(_05_),
    .Y(_10_)
  );
  NAND2X1 _15_ (
    .A(_05_),
    .B(_04_),
    .Y(_07_)
  );
  NAND2X1 _16_ (
    .A(_03_),
    .B(_06_),
    .Y(_08_)
  );
  NOR2X1 _17_ (
    .A(_07_),
    .B(_08_),
    .Y(_13_)
  );
  NAND2X1 _18_ (
    .A(_06_),
    .B(_04_),
    .Y(_09_)
  );
  NOR2X1 _19_ (
    .A(_09_),
    .B(_10_),
    .Y(_12_)
  );
  XOR2X1 _20_ (
    .A(_07_),
    .B(_08_),
    .Y(_11_)
  );
  assign _03_ = in0;
  assign _05_ = in2;
  assign out0 = _10_;
  assign _06_ = in3;
  assign _04_ = in1;
  assign out3 = _13_;
  assign out2 = _12_;
  assign out1 = _11_;
endmodule
