/* Generated by Yosys 0.53+60 (git sha1 209df95fb, g++ 10.5.0-1ubuntu1~20.04 -fPIC -O3) */

module top(in0, in1, in2, in3, in4, in5, in6, in7, out0, out1, out2, out3, out4, out5, out6, out7);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input in4;
  wire in4;
  input in5;
  wire in5;
  input in6;
  wire in6;
  input in7;
  wire in7;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  output out4;
  wire out4;
  output out5;
  wire out5;
  output out6;
  wire out6;
  output out7;
  wire out7;
  AND2X2 _132_ (
    .A(_065_),
    .B(_061_),
    .Y(_124_)
  );
  NAND2X1 _133_ (
    .A(_063_),
    .B(_067_),
    .Y(_069_)
  );
  NAND2X1 _134_ (
    .A(_066_),
    .B(_064_),
    .Y(_070_)
  );
  INVX1 _135_ (
    .A(_067_),
    .Y(_071_)
  );
  INVX1 _136_ (
    .A(_064_),
    .Y(_072_)
  );
  NAND2X1 _137_ (
    .A(_063_),
    .B(_066_),
    .Y(_073_)
  );
  NOR3X1 _138_ (
    .A(_073_),
    .B(_071_),
    .C(_072_),
    .Y(_074_)
  );
  AOI21X1 _139_ (
    .A(_069_),
    .B(_070_),
    .C(_074_),
    .Y(_075_)
  );
  NAND2X1 _140_ (
    .A(_065_),
    .B(_063_),
    .Y(_076_)
  );
  OR2X2 _141_ (
    .A(_070_),
    .B(_076_),
    .Y(_077_)
  );
  NAND2X1 _142_ (
    .A(_062_),
    .B(_067_),
    .Y(_078_)
  );
  NAND2X1 _143_ (
    .A(_065_),
    .B(_064_),
    .Y(_079_)
  );
  NAND2X1 _144_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  NAND2X1 _145_ (
    .A(_077_),
    .B(_080_),
    .Y(_081_)
  );
  OAI21X1 _146_ (
    .A(_078_),
    .B(_081_),
    .C(_077_),
    .Y(_082_)
  );
  NAND2X1 _147_ (
    .A(_075_),
    .B(_082_),
    .Y(_083_)
  );
  XOR2X1 _148_ (
    .A(_075_),
    .B(_082_),
    .Y(_084_)
  );
  NAND3X1 _149_ (
    .A(_084_),
    .B(_062_),
    .C(_068_),
    .Y(_085_)
  );
  NAND2X1 _150_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NAND2X1 _151_ (
    .A(_063_),
    .B(_068_),
    .Y(_087_)
  );
  NAND3X1 _152_ (
    .A(_073_),
    .B(_067_),
    .C(_064_),
    .Y(_088_)
  );
  XOR2X1 _153_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  XOR2X1 _154_ (
    .A(_089_),
    .B(_086_),
    .Y(_090_)
  );
  NAND2X1 _155_ (
    .A(_062_),
    .B(_066_),
    .Y(_091_)
  );
  NOR2X1 _156_ (
    .A(_076_),
    .B(_091_),
    .Y(_092_)
  );
  XNOR2X1 _157_ (
    .A(_076_),
    .B(_091_),
    .Y(_093_)
  );
  NAND2X1 _158_ (
    .A(_067_),
    .B(_061_),
    .Y(_094_)
  );
  NOR2X1 _159_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  NOR2X1 _160_ (
    .A(_095_),
    .B(_092_),
    .Y(_096_)
  );
  XOR2X1 _161_ (
    .A(_078_),
    .B(_081_),
    .Y(_097_)
  );
  INVX1 _162_ (
    .A(_097_),
    .Y(_098_)
  );
  XNOR2X1 _163_ (
    .A(_097_),
    .B(_096_),
    .Y(_099_)
  );
  NAND3X1 _164_ (
    .A(_099_),
    .B(_061_),
    .C(_068_),
    .Y(_100_)
  );
  OAI21X1 _165_ (
    .A(_096_),
    .B(_098_),
    .C(_100_),
    .Y(_101_)
  );
  NAND2X1 _166_ (
    .A(_062_),
    .B(_068_),
    .Y(_102_)
  );
  XNOR2X1 _167_ (
    .A(_102_),
    .B(_084_),
    .Y(_103_)
  );
  NAND2X1 _168_ (
    .A(_103_),
    .B(_101_),
    .Y(_104_)
  );
  XOR2X1 _169_ (
    .A(_094_),
    .B(_093_),
    .Y(_105_)
  );
  NAND2X1 _170_ (
    .A(_065_),
    .B(_062_),
    .Y(_106_)
  );
  NAND2X1 _171_ (
    .A(_066_),
    .B(_061_),
    .Y(_107_)
  );
  NOR2X1 _172_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  NAND2X1 _173_ (
    .A(_108_),
    .B(_105_),
    .Y(_109_)
  );
  NAND2X1 _174_ (
    .A(_061_),
    .B(_068_),
    .Y(_110_)
  );
  XOR2X1 _175_ (
    .A(_110_),
    .B(_099_),
    .Y(_111_)
  );
  NOR2X1 _176_ (
    .A(_111_),
    .B(_109_),
    .Y(_112_)
  );
  XOR2X1 _177_ (
    .A(_103_),
    .B(_101_),
    .Y(_113_)
  );
  NAND2X1 _178_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  NAND2X1 _179_ (
    .A(_104_),
    .B(_114_),
    .Y(_115_)
  );
  XOR2X1 _180_ (
    .A(_090_),
    .B(_115_),
    .Y(_129_)
  );
  NAND2X1 _181_ (
    .A(_064_),
    .B(_068_),
    .Y(_116_)
  );
  INVX1 _182_ (
    .A(_069_),
    .Y(_117_)
  );
  INVX1 _183_ (
    .A(_074_),
    .Y(_118_)
  );
  MUX2X1 _184_ (
    .A(_118_),
    .B(_117_),
    .S(_116_),
    .Y(_119_)
  );
  NOR2X1 _185_ (
    .A(_086_),
    .B(_089_),
    .Y(_120_)
  );
  NAND2X1 _186_ (
    .A(_089_),
    .B(_086_),
    .Y(_121_)
  );
  AOI21X1 _187_ (
    .A(_121_),
    .B(_104_),
    .C(_120_),
    .Y(_122_)
  );
  NAND2X1 _188_ (
    .A(_119_),
    .B(_122_),
    .Y(_123_)
  );
  OAI21X1 _189_ (
    .A(_069_),
    .B(_116_),
    .C(_123_),
    .Y(_131_)
  );
  XOR2X1 _190_ (
    .A(_106_),
    .B(_107_),
    .Y(_125_)
  );
  XOR2X1 _191_ (
    .A(_108_),
    .B(_105_),
    .Y(_126_)
  );
  XOR2X1 _192_ (
    .A(_112_),
    .B(_113_),
    .Y(_128_)
  );
  XOR2X1 _193_ (
    .A(_119_),
    .B(_122_),
    .Y(_130_)
  );
  XOR2X1 _194_ (
    .A(_109_),
    .B(_111_),
    .Y(_127_)
  );
  assign _065_ = in4;
  assign _062_ = in1;
  assign _063_ = in2;
  assign _066_ = in5;
  assign _067_ = in6;
  assign _061_ = in0;
  assign _064_ = in3;
  assign _068_ = in7;
  assign out0 = _124_;
  assign out5 = _129_;
  assign out7 = _131_;
  assign out1 = _125_;
  assign out2 = _126_;
  assign out4 = _128_;
  assign out6 = _130_;
  assign out3 = _127_;
endmodule
